/**
 * Component 5 — GitHub Integration (The Delivery)
 * Creates a branch, commits the fix, and opens a Pull Request.
 */

const { Octokit } = require('@octokit/rest');
const fs = require('fs');
const path = require('path');

function getOctokit() {
  if (!process.env.GITHUB_TOKEN) throw new Error('GITHUB_TOKEN is not set in .env');
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
}

/**
 * Full flow: create branch -> commit fix -> open PR
 * @param {object} params
 * @returns {object} { prUrl, prNumber, branchName }
 */
async function createFixPR({ contextPackage, aiResult, fixResult, errorLogId }) {
  const octokit = getOctokit();
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;

  if (!owner || !repo) {
    throw new Error('GITHUB_OWNER and GITHUB_REPO must be set in .env');
  }

  const { filePath, errorType, lineNumber } = contextPackage;
  const { explanation, confidenceScore, errorCategory } = aiResult;
  const { newContent, diffOutput, validationPassed } = fixResult;

  // 1. Get the default branch SHA (handle empty repos)
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;

  let baseSha;
  try {
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    baseSha = refData.object.sha;
  } catch {
    // Repo is empty — create an initial README commit first
    console.log('[GitHub] Repo is empty. Creating initial commit...');
    const initContent = Buffer.from('# AI Debug Test\nThis repo receives auto-fix PRs from AI Debugging Agent.\n', 'utf8').toString('base64');
    await octokit.repos.createOrUpdateFileContents({
      owner, repo,
      path: 'README.md',
      message: 'chore: initial commit',
      content: initContent,
    });
    // Now get the SHA
    const { data: refData } = await octokit.git.getRef({
      owner, repo,
      ref: `heads/${defaultBranch}`,
    });
    baseSha = refData.object.sha;
    console.log('[GitHub] Initial commit created.');
  }

  // 2. Create a new fix branch
  const timestamp = Date.now();
  const safeErrorType = (errorType || 'error').toLowerCase().replace(/[^a-z0-9]/g, '-');
  const branchName = `fix/auto-${safeErrorType}-${timestamp}`;

  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });
  console.log(`[GitHub] Branch created: ${branchName}`);

  // 3 & 4. Commit fix — real source file if available, else a markdown fix report
  let repoFilePath, commitMessage, commitContent;

  if (newContent && filePath && filePath !== 'unknown') {
    repoFilePath = normalizeRepoPath(filePath);
    let currentFileSha = null;
    try {
      const { data: fileData } = await octokit.repos.getContent({
        owner, repo, path: repoFilePath, ref: defaultBranch,
      });
      currentFileSha = fileData.sha;
    } catch {
      console.warn(`[GitHub] File not found in repo — will create it.`);
    }
    commitContent = Buffer.from(newContent, 'utf8').toString('base64');
    commitMessage = `fix(auto): ${errorType} in ${path.basename(filePath)} line ${lineNumber}\n\nAuto-fix by AI Debugging Agent\nConfidence: ${confidenceScore}%`;
    await octokit.repos.createOrUpdateFileContents({
      owner, repo, path: repoFilePath, message: commitMessage,
      content: commitContent, sha: currentFileSha, branch: branchName,
    });
  } else {
    // No source file — create a markdown fix report in the repo
    repoFilePath = `ai-fixes/fix-report-${Date.now()}.md`;
    const reportContent = buildFixReport({ contextPackage, aiResult });
    commitContent = Buffer.from(reportContent, 'utf8').toString('base64');
    commitMessage = `fix(auto): AI fix report for ${errorType}\n\nAuto-generated by AI Debugging Agent\nConfidence: ${confidenceScore}%`;
    await octokit.repos.createOrUpdateFileContents({
      owner, repo, path: repoFilePath, message: commitMessage,
      content: commitContent, branch: branchName,
    });
  }

  console.log(`[GitHub] File committed: ${repoFilePath}`);

  // 5. Open the Pull Request
  const prBody = buildPRBody({
    contextPackage,
    aiResult,
    fixResult,
    branchName,
    defaultBranch,
  });

  const { data: prData } = await octokit.pulls.create({
    owner,
    repo,
    title: `[Auto-Fix] ${errorType}: ${contextPackage.errorMessage?.substring(0, 80) || 'Error detected'}`,
    body: prBody,
    head: branchName,
    base: defaultBranch,
  });

  // 6. Add labels
  try {
    await octokit.issues.addLabels({
      owner,
      repo,
      issue_number: prData.number,
      labels: ['auto-fix', 'needs-review', confidenceScore >= 80 ? 'high-confidence' : 'low-confidence'],
    });
  } catch {
    // Labels may not exist yet — not critical
  }

  console.log(`[GitHub] PR opened: ${prData.html_url}`);

  // 7. Confidence-based auto-merge
  let autoMerged = false;
  const AUTO_MERGE_THRESHOLD = parseInt(process.env.AUTO_MERGE_THRESHOLD || '95', 10);

  if (confidenceScore >= AUTO_MERGE_THRESHOLD && fixResult.validationPassed) {
    try {
      await octokit.pulls.merge({
        owner,
        repo,
        pull_number: prData.number,
        commit_title: `[Auto-Merged] ${errorType} fix — ${confidenceScore}% confidence`,
        commit_message: `Auto-merged by AI Debugging Agent.\nConfidence: ${confidenceScore}%\nSyntax validation: passed`,
        merge_method: 'squash',
      });
      autoMerged = true;
      console.log(`[GitHub] PR auto-merged (confidence: ${confidenceScore}% >= ${AUTO_MERGE_THRESHOLD}%)`);
    } catch (err) {
      console.warn(`[GitHub] Auto-merge failed: ${err.message}`);
    }
  } else if (confidenceScore < 70) {
    console.log(`[GitHub] Low confidence (${confidenceScore}%) — skipping auto-merge, manual review needed.`);
  }

  return {
    prUrl: prData.html_url,
    prNumber: prData.number,
    branchName,
    autoMerged,
  };
}

function buildPRBody({ contextPackage, aiResult, fixResult, branchName, defaultBranch }) {
  const { errorMessage, errorType, filePath, lineNumber, stackTrace } = contextPackage;
  const { explanation, confidenceScore, errorCategory } = aiResult;
  const { diffOutput, validationPassed } = fixResult;

  const syntaxBadge = validationPassed ? '✅ Passed' : '⚠️ Failed';
  const confidenceBadge = confidenceScore >= 80 ? '🟢' : confidenceScore >= 50 ? '🟡' : '🔴';

  return `## 🤖 Auto-Fix Pull Request

> Generated automatically by **AI Debugging Agent**

---

### 🐛 Error Detected
| Field | Value |
|-------|-------|
| **Type** | \`${errorType}\` |
| **File** | \`${filePath}\` |
| **Line** | ${lineNumber} |
| **Category** | ${errorCategory} |

**Error Message:**
\`\`\`
${errorMessage}
\`\`\`

**Stack Trace:**
\`\`\`
${stackTrace || 'Not available'}
\`\`\`

---

### 🧠 AI Analysis
${explanation}

**Confidence Score:** ${confidenceBadge} ${confidenceScore}%  
**Syntax Validation:** ${syntaxBadge}

---

### 📋 Code Diff
\`\`\`diff
${diffOutput?.substring(0, 3000) || 'Diff not available'}
\`\`\`

---

### ⚠️ Review Checklist
- [ ] Review the suggested fix carefully before merging
- [ ] Run tests against the changed file
- [ ] Verify the fix doesn't break related functionality
- [ ] Check that the AI explanation matches the actual bug

---
*This PR was auto-generated. Always review AI fixes before merging to production.*`;
}

function buildFixReport({ contextPackage, aiResult }) {
  const { errorMessage, errorType, stackTrace } = contextPackage;
  const { explanation, fixedCode, confidenceScore } = aiResult;
  return `# 🤖 AI Fix Report

**Error Type:** \`${errorType}\`
**Error Message:** ${errorMessage}
**Confidence:** ${confidenceScore}%

## Stack Trace
\`\`\`
${stackTrace || 'Not available'}
\`\`\`

## AI Explanation
${explanation}

## Suggested Fix
\`\`\`javascript
${fixedCode || 'See explanation above'}
\`\`\`

---
*Auto-generated by AI Debugging Agent using Groq Llama 3*
`;
}

function normalizeRepoPath(filePath) {
  const path = require('path');

  // If WATCH_SOURCE_PATH is set, strip it to get the path relative to the repo root
  if (process.env.WATCH_SOURCE_PATH) {
    const sourcePath = path.resolve(process.env.WATCH_SOURCE_PATH);
    const resolvedFile = path.resolve(filePath);
    if (resolvedFile.startsWith(sourcePath)) {
      return resolvedFile
        .substring(sourcePath.length)
        .replace(/\\/g, '/')
        .replace(/^\//, '');
    }
  }

  // Fallback: strip drive letter and convert to forward slashes
  return filePath
    .replace(/^[A-Z]:\\/, '')
    .replace(/\\/g, '/')
    .replace(/^\//, '');
}

module.exports = { createFixPR };
